const publicAsset = <TFolder extends string, TFile extends string>(
    folder: TFolder,
    file: TFile,
) => `/${folder}/${file}` as const;

export const assets = {
    profile: "/pfp.jpg",
    resume: "/resume/Jake Finlay Resume.pdf",

    devIcons: {
        apollo: publicAsset("dev-icons", "apollo.svg"),
        bash: publicAsset("dev-icons", "bash.svg"),
        csharp: publicAsset("dev-icons", "csharp.svg"),
        css: publicAsset("dev-icons", "css.svg"),
        d3: publicAsset("dev-icons", "d3.svg"),
        express: publicAsset("dev-icons", "express.svg"),
        fm: publicAsset("dev-icons", "fm.svg"),
        git: publicAsset("dev-icons", "git.svg"),
        graphql: publicAsset("dev-icons", "graphql.svg"),
        gsap: publicAsset("dev-icons", "gsap.svg"),
        html: publicAsset("dev-icons", "html.svg"),
        java: publicAsset("dev-icons", "java.svg"),
        javascript: publicAsset("dev-icons", "js.svg"),
        linux: publicAsset("dev-icons", "linux.svg"),
        mongodb: publicAsset("dev-icons", "mongodb.svg"),
        mongoose: publicAsset("dev-icons", "mongoose.svg"),
        next: publicAsset("dev-icons", "next.svg"),
        node: publicAsset("dev-icons", "node.svg"),
        npm: publicAsset("dev-icons", "npm.svg"),
        nx: publicAsset("dev-icons", "nx.svg"),
        pnpm: publicAsset("dev-icons", "pnpm.svg"),
        postgresql: publicAsset("dev-icons", "postgresql.svg"),
        python: publicAsset("dev-icons", "python.svg"),
        react: publicAsset("dev-icons", "re.svg"),
        redux: publicAsset("dev-icons", "redux.svg"),
        s: publicAsset("dev-icons", "s.svg"),
        tailwind: publicAsset("dev-icons", "tail.svg"),
        three: publicAsset("dev-icons", "three.svg"),
        typescript: publicAsset("dev-icons", "ts.svg"),
    },

    fullstackPics: {
        banklerDashboard: publicAsset(
            "fullstack-pics",
            "bankler-dashboard.png",
        ),
        banklerMyBanks: publicAsset("fullstack-pics", "bankler-my-banks.png"),
        banklerPaymentTransfer: publicAsset(
            "fullstack-pics",
            "bankler-payment-transfer.png",
        ),
        banklerSignIn: publicAsset("fullstack-pics", "bankler-sign-in.png"),
        banklerTransactionHistory: publicAsset(
            "fullstack-pics",
            "bankler-transaction-history.png",
        ),
        linkRippleDashboard: publicAsset(
            "fullstack-pics",
            "link-ripple-dashboard.png",
        ),
        linkRippleLanding: publicAsset(
            "fullstack-pics",
            "link-ripple-landing.png",
        ),
        linkRippleLinks: publicAsset("fullstack-pics", "link-ripple-links.png"),
    },

    misc: {
        arrow: publicAsset("misc", "arrow.svg"),
        b1: publicAsset("misc", "b1.svg"),
        b4: publicAsset("misc", "b4.svg"),
        b5: publicAsset("misc", "b5.svg"),
        background: publicAsset("misc", "bg.png"),
        ball1: publicAsset("misc", "ball1.png"),
        ball2: publicAsset("misc", "ball2.png"),
        ball3: publicAsset("misc", "ball3.png"),
        ball4: publicAsset("misc", "ball4.png"),
        carrent: publicAsset("misc", "carrent.png"),
        close: publicAsset("misc", "close.svg"),
        confetti: publicAsset("misc", "confetti.gif"),
        exp1: publicAsset("misc", "exp1.svg"),
        exp2: publicAsset("misc", "exp2.svg"),
        exp3: publicAsset("misc", "exp3.svg"),
        exp4: publicAsset("misc", "exp4.svg"),
        footerGrid: publicAsset("misc", "footer-grid.svg"),
        github: publicAsset("misc", "github.png"),
        grid: publicAsset("misc", "grid.svg"),
        heroBackground: publicAsset("misc", "herobg.png"),
        jobit: publicAsset("misc", "jobit.png"),
        location: publicAsset("misc", "location.svg"),
        logo: publicAsset("misc", "logo.svg"),
        menu: publicAsset("misc", "menu.svg"),
        tripguide: publicAsset("misc", "tripguide.png"),
    },

    projectPics: {
        barChart: publicAsset("project-pics", "bar-chart.png"),
        calculator: publicAsset("project-pics", "calculator.png"),
        choroplethMap: publicAsset("project-pics", "choropleth-map.png"),
        exerciseTracker: publicAsset("project-pics", "exercise-tracker.png"),
        fileMetadata: publicAsset("project-pics", "file-metadata.png"),
        heatMap: publicAsset("project-pics", "heat-map.png"),
        legacyPortfolio: publicAsset("project-pics", "legacy-portfolio.png"),
        logo: publicAsset("project-pics", "logo.png"),
        markdownPreviewer: publicAsset(
            "project-pics",
            "markdown-previewer.png",
        ),
        memeSoundboard: publicAsset("project-pics", "meme-soundboard.png"),
        pomodoroClock: publicAsset("project-pics", "pomodoro-clock.png"),
        productLandingPage: publicAsset(
            "project-pics",
            "product-landing-page.png",
        ),
        quoteGenerator: publicAsset("project-pics", "quote-generator.png"),
        requestHeaderParser: publicAsset(
            "project-pics",
            "request-header-parser.png",
        ),
        scatterPlot: publicAsset("project-pics", "scatter-plot.png"),
        surveyForm: publicAsset("project-pics", "survey-form.png"),
        technicalDocumentation: publicAsset(
            "project-pics",
            "technical-documentation.png",
        ),
        timestamp: publicAsset("project-pics", "timestamp.png"),
        treemapDiagram: publicAsset("project-pics", "treemap-diagram.png"),
        tributePage: publicAsset("project-pics", "tribute-page.png"),
        underConstruction: publicAsset(
            "project-pics",
            "under-construction.png",
        ),
        urlShortener: publicAsset("project-pics", "url-shortener.png"),
    },

    socialIcons: {
        document: publicAsset("social-icons", "document.svg"),
        git: publicAsset("social-icons", "git.svg"),
        githubButton: publicAsset("social-icons", "git2.svg"),
        instagram: publicAsset("social-icons", "insta.svg"),
        link: publicAsset("social-icons", "link.svg"),
        mail: publicAsset("social-icons", "mail.svg"),
        twitter: publicAsset("social-icons", "twit.svg"),
        wha: publicAsset("social-icons", "wha.svg"),
    },

    workIcons: {
        evertz: publicAsset("work-icons", "evertz.svg"),
        sbww: publicAsset("work-icons", "sbww.png"),
        scf: publicAsset("work-icons", "scf.png"),
    },
} as const;
